# Generated by Django 3.0.6 on 2020-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default=1, upload_to='image_folder/'),
            preserve_default=False,
        ),
    ]
