# Generated by Django 3.0.6 on 2020-05-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200511_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name_plural': 'commmmments'},
        ),
    ]
